version: '3.3'
services:
  mongo:
    ports:
    - '27017:27017'
    expose:
      - 27017
    container_name: mongodb
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongo
    - MONGO_INITDB_ROOT_PASSWORD=12345
    - MONGO_INITDB_DATABASE=unipeak-data-base
    image: mongo
    volumes:
    - mongo_data:/var/lib/mongodb/data
    - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: 12345
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongo://mongo:12345@mongo:27017/unipeak-data-base
    depends_on:
      - mongo
volumes: 
  mongo_data:
    external: true
    name: unipeak-volume